# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    - go mod tidy
builds:
- env:
    # goreleaser does not work with CGO, it could also complicate
    # they are unable to install libraries.
    - CGO_ENABLED=0
  main: ./cmd/artifactory/main.go
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    # use 'go tool nm <path_to_binary> | grep Version' to find the Version variable path
    - '-s -w -X github.com/jfrog/artifactory-secrets-plugin.Version=v{{ .Version }}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}'
snapshot:
  name_template: '{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true